version: '3'

services:


          go:
            image: leo812993/dockerleanote_go:latest
            volumes:
              - "/home/leo/docker_leanote/gopackage:/home/root/gopackage"
              - "/home/leo/docker_leanote/data/data:/home/root/data"
              #- "/Users/leo/Documents/works/webdata/letsencrypt:/etc/letsencrypt"
            container_name: leanote
            #environment:
            #    WEB_HTTPS: "ON"
               
            build: 
              context: .
              args:
                buildno: 1
            ports: 
              - "8080:9000"
              - "27017:27017"
                  #- "443:443"

            restart: always

            privileged: true

          


