version: '3'

services:


          go:
            #image: leo812993/centos_nginx:v2.1
            volumes:
              - "/home/leo/works/docker_leanote/gopackage:/home/root/gopackage"
              - "/home/leo/works/docker_leanote/data:/home/root/data"
              #- "/Users/leo/Documents/works/webdata/letsencrypt:/etc/letsencrypt"
            container_name: leanote
            #environment:
            #    WEB_HTTPS: "ON"
               
            build: 
              context: .
              args:
                buildno: 1
                ports: 
                   "9000:9000"
                  #- "443:443"

            restart: always

            privileged: true

          


