version: '3'

services:


          go:
            image: leo812993/dockerleanote_go:latest
            volumes:
              - "/Users/leo/Documents/works/DockerLeanote/gopackage:/home/root/gopackage"
              - "/Users/leo/Documents/works/DockerLeanote/data:/home/root/data"
              #- "/Users/leo/Documents/works/webdata/letsencrypt:/etc/letsencrypt"
            container_name: leanote
            #environment:
            #    WEB_HTTPS: "ON"
               
            build: 
              context: .
              args:
                buildno: 1
            ports: 
              - "9000:9000"
                  #- "443:443"

            restart: always

            privileged: true

          


